/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import Home from "./script/Home"
import List from "./script/List"
import GameUI from "./script/GameUI"
import GameControl from "./script/GameControl"
import Gold from "./script/Gold"
import Pillar1 from "./script/Pillar1"
import Pillar2 from "./script/Pillar2"
import Pillar3 from "./script/Pillar3"
import Tomato from "./script/Tomato"
import Trap from "./script/Trap"

export default class GameConfig {
    static init() {
        //注册Script或者Runtime引用
        let reg = Laya.ClassUtils.regClass;
		reg("script/Home.js",Home);
		reg("script/List.js",List);
		reg("script/GameUI.js",GameUI);
		reg("script/GameControl.js",GameControl);
		reg("script/Gold.js",Gold);
		reg("script/Pillar1.js",Pillar1);
		reg("script/Pillar2.js",Pillar2);
		reg("script/Pillar3.js",Pillar3);
		reg("script/Tomato.js",Tomato);
		reg("script/Trap.js",Trap);
    }
}
GameConfig.width = 1334;
GameConfig.height = 750;
GameConfig.scaleMode ="fixedwidth";
GameConfig.screenMode = "none";
GameConfig.alignV = "top";
GameConfig.alignH = "left";
GameConfig.startScene = "home/home.scene";
GameConfig.mainScene = "main/main.scene";
GameConfig.sceneRoot = "";
GameConfig.debug = false;
GameConfig.stat = false;
GameConfig.physicsDebug = false;
GameConfig.exportSceneToJson = true;

GameConfig.init();
